# Generated by Django 6.0.2 on 2026-02-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cca2', models.CharField(max_length=2)),
                ('capital', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('flag', models.URLField(blank=True, null=True)),
                ('currencies', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
